railsBBS/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'posts#index'

end

railsBBS/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :text,
  presence: {message: "入力してください"},
  length: {minimum: 3, message: "too short!"}
  belongs_to :user
end

railsBBS/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

railsBBS/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

railsBBS/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @users = User.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params) # formからの値を取得
    if current_user != nil
      @post.user_id = current_user.id
    end

    if @post.save # DBに保存
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params[:post].permit(:title, :text) # form のtitleのみ許可
    end

    def set_post
      @post = Post.find(params[:id])
      if @post.user_id != nil
        @post.user = User.find(@post.user_id)
      end
    end
end

railsBBS/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_name params[:name]
    puts(user)
    puts(params[:pass])


    if user && user.authenticate(params[:pass])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = "Invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

railsBBS/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) # formからの値を取得
    if @user.save # DBに保存
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params[:user].permit(:name, :password)
    end

   def set_user
      @user = User.find(params[:id])
   end

end

railsBBS/app/helpers/application_helper.rb
module ApplicationHelper
end

railsBBS/app/helpers/posts_helper.rb
module PostsHelper
end

railsBBS/app/helpers/sessions_helper.rb
module SessionsHelper
end

railsBBS/app/helpers/users_helper.rb
module UsersHelper
end

railsBBS/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBBS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "Rails BBS", posts_path %></h1>

<% if current_user == nil %>
  <div class="login"><%= link_to "ログイン", new_session_path %></div>
<% else %>
  <div class="login"><%= link_to "ログアウト", session_path(current_user.id), method: :delete, data: {confirm: 'ログアウトしますか?'} %></div>
<p>
  Login User:<%= current_user.name %>
</p>
<% end %>



<%= yield %>

</body>
</html>

railsBBS/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <% if @post.errors.any? %>
  <%= @post.errors.messages[:title][0]  %>
  <% end %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_field :text %>
  <% if @post.errors.any? %>
  <%= @post.errors.messages[:text][0]  %>
  <% end %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<p>
<% if current_user != nil  %>
  loginUser: <%= current_user.name %>
<% else %>
  you are guest
<% end %>
</p>

railsBBS/app/views/posts/index.html.erb
<h1>Posts</h1>
<div class="post">
  <ul class="post__list">
    <% @posts.each do |post| %>
    <li class="post__item">
      <div>
        <span><%= link_to post.id, post_path(post.id) %></span>
        <% if post.user != nil  %>
          <span><%= link_to post.user.name, user_path(post.user.id) %></span>
        <% end %>
        <div class="post__edit">
          <%= link_to "[Edit]", edit_post_path(post.id) %>
          <%= link_to "[x]", post_path(post.id), method: :delete, data: {confirm: "are you sure?"} %>
        </div>
      </div>
      <div class="post-item__text">
        <div><%= post.title %></div>
        <div><%= post.text %></div>
      </div>
    </li>
    <% end %>
  </ul>

  <div>
    <span>投稿</span>
    <% @post = Post.new %>
    <%= render 'form' %>
  </div>

</div>

<p>
  <%= link_to "Add New Post", new_post_path %>
</p>
<p>
  <%= link_to "Add New User", new_user_path %>
</p>

railsBBS/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

railsBBS/app/views/posts/show.html.erb
<p><%= @post.title %></p>
<p><%= @post.text %></p>

railsBBS/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <% if @user.errors.any? %>
  <%= @user.errors.messages[:name][0]  %>
  <% end %>
</p>

<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <% if @user.errors.any? %>
  <%= @user.errors.messages[:password][0]  %>
  <% end %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

railsBBS/app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

railsBBS/app/views/users/index.html.erb
<h1>Users</h1>

<ul class="user">
  <% @users.each do |user| %>
  <li class="user__name">
    <%= link_to user.id, user_path(user.id) %>
    <%= user.name %>
    <%= link_to "[Edit]", edit_user_path(user.id) %>
    <%= link_to "[Delete]", user_path(user.id), method: :delete, data: {confirm: "are you sure?"} %>
  </li>
  <% end %>
</ul>

<%= link_to "Add New", new_user_path %>

railsBBS/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

railsBBS/app/views/users/show.html.erb
<p><%= @user.name %></p>